name: Build and Release module

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name to build (e.g., v1.0.0)'
        required: true
        type: string

jobs:
  build:
    name: Build China_Smartmanager
    runs-on: ubuntu-22.04
    permissions:
      contents: write  # Give write permission to push tags
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures the full repository is checked out

      - name: Create Feature Enhancer ZIP
        run: |
          zip -r China_SmartManager-${{ github.event.inputs.tag_name }}.zip . \
          -x ".git*" -x ".github*" -x "README.md"

      - name: Create a Tag
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git tag ${{ github.event.inputs.tag_name }}
          git push origin ${{ github.event.inputs.tag_name }}

      - name: Upload Release to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: China_SmartManager-${{ github.event.inputs.tag_name }}.zip
          tag_name: ${{ github.event.inputs.tag_name }}
          release_name: China_SmartManager ${{ github.event.inputs.tag_name }}
          body: |
            New release of China_SmartManager: **${{ github.event.inputs.tag_name }}**
